name: "Deploy on master"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      
      - name: Install NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint links
        run: npm run lint-links

      - name: Build website
        run: PUBLIC_URL="/notification-documentation/" npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/.vuepress/dist
          user_name: 'actions-user'
          user_email: 'actions@github.com'
          force_orphan: true

      - name: Notify Slack channel if this job failed
        if: ${{ failure() }}
        run: |
          json='{"text":"<!here> CI is failing in <https://github.com/cds-snc/notification-documentation/actions/runs/'${{ github.run_id }}'|notification-documentation> !"}'
          curl -X POST -H 'Content-type: application/json' --data "$json"  ${{ secrets.SLACK_WEBHOOK }}
